#osp.appcontrol.CONTACT
Title=APPCONTROL_CONTACT
Vendor=Samsung
Overridable=No
OPID_Count=4
OPID_0=osp.appcontrol.operation.PICK
OPID_1=osp.appcontrol.operation.ADD
OPID_2=osp.appcontrol.operation.EDIT
OPID_3=osp.appcontrol.operation.MAIN
Path=ContactAppControl
LaunchType=2
#osp.appcontrol.CALENDAR
Title=APPCONTROL_CALENDAR
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.PICK
Path=CalendarAppControl
LaunchType=2
#osp.appcontrol.TODO
Title=APPCONTROL_TODO
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.PICK
Path=CalendarAppControl
LaunchType=2
#osp.appcontrol.BT
Title=APPCONTROL_BT
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.PICK
Path=BluetoothAppControl
LaunchType=2
#osp.appcontrol.DIAL
Title=APPCONTROL_DIAL
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=AppControl
LaunchType=2
#osp.appcontrol.CALL
Title=APPCONTROL_CALL
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=AppControl
LaunchType=2
#osp.appcontrol.BROWSER
Title=APPCONTROL_BROWSER
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=BrowserAppControl
LaunchType=2
#osp.appcontrol.MEDIA
Title=APPCONTROL_MEDIA
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.PICK
Path=MediaAppControl
LaunchType=2
#osp.appcontrol.MESSAGE
Title=APPCONTROL_MESSAGE
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.EDIT
Path=MessageAppControl
LaunchType=2
#osp.appcontrol.EMAIL
Title=APPCONTROL_EMAIL
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.EDIT
Path=MessageAppControl
LaunchType=2
#osp.appcontrol.IMAGE
Title=APPCONTROL_IMAGE
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.VIEW
Path=MediaAppControl
LaunchType=2
#osp.appcontrol.VIDEO
Title=APPCONTROL_VIDEO
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.VIEW
Path=MediaAppControl
LaunchType=2
#osp.appcontrol.AUDIO
Title=APPCONTROL_AUDIO
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.PLAY
Path=MediaAppControl
LaunchType=2
#osp.appcontrol.CAMERA
Title=APPCONTROL_CAMERA
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.CAPTURE
Path=CameraAppControl
LaunchType=2
#osp.appcontrol.INTERNETPROFILE 
Title=APPCONTROL_INTERNETPROFILE 
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.PICK
Path=InternetProfileAppControl
LaunchType=2
#osp.appcontrol.SIGNIN
Title=APPCONTROL_SIGNIN
Overridable=No
Vendor=Samsung
OPID_Count=4
OPID_0=osp.appcontrol.operation.SIGNIN
OPID_1=osp.appcontrol.operation.SIGNOUT
OPID_2=osp.appcontrol.operation.TWO_PHASE_SIGNIN_ODC
OPID_3=osp.appcontrol.operation.DELETE_ACCOUNT
Path=SignInAppControl
LaunchType=2
#osp.appcontrol.EMAIL_SETTING
Title=APPCONTROL_EMAIL_SETTING
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=MessageAppControl
LaunchType=2
#osp.appcontrol.EMAIL_VIEW
Title=APPCONTROL_EMAIL_VIEW
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.VIEW
Path=MessageAppControl
LaunchType=2
#osp.appcontrol.COMMERCE
Title=APPCONTROL_COMMERCE
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=CommerceAppControl
LaunchType=2
#osp.appcontrol.SEVEN.AGENT
Title=APPCONTROL_SEVEN_AGENT
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=AppControl
LaunchType=2
#osp.appcontrol.ASTORE
Title=APPCONTROL_ASTORE
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=1rfjf7285p
LaunchType=3
#osp.appcontrol.SNSAUTH
Title=APPCONTROL_SNSAUTH
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.SINGIN
Path=SnsAuthAppControl
LaunchType=2
#osp.appcontrol.TIMER
Title=APPCONTROL_TIMER
Overridable=No
Vendor=Samsung
OPID_Count=2
OPID_0=osp.appcontrol.operation.ADD
OPID_1=osp.appcontrol.operation.DELETE
Path=AppControl
LaunchType=2
#osp.appcontrol.SETTINGS
Title=APPCONTROL_SETTINGS
Overridable=No
Vendor=Samsung
OPID_Count=1
OPID_0=osp.appcontrol.operation.MAIN
Path=SettingAppControl
LaunchType=2