#Version
Version=2.0
#msysserver
Name=msysserver
DllName=msysserver
CID_UUID=DCE74BCD-6096-4617-A8A1-7F23F3DA9E34
Flags=0
#mapppackagemanager
Name=mappclient
DllName=mosp
CID_UUID=68864C42-76D2-42db-85BC-88DAB0132CD3
Flags=0
#mservermanager
Name=mappserver
DllName=mappserver
CID_UUID=2898d1df-bd59-4eb2-8497-1fc8a1f2e094
Flags=0
#mappserver
Name=mappserver
DllName=mappserver
CID_UUID=33c84e7e-6843-4174-a362-d74f72f4a2fe
Flags=0
#mappserverstub
Name=mappserver
DllName=mappserver
CID_UUID=ec62f26f-a949-4327-baf9-236c3deb2972
Flags=0
#mappipcservermanager
Name=mappserver
DllName=mappserver
CID_UUID=236f1c9c-f552-4adf-bc72-c8c45ce4a49d
Flags=0
#mappNotificationManager
Name=mappclient
DllName=mosp
CID_UUID=6A407120-86B2-4b5d-9F1A-4A5B643323E2
Flags=0
#mad
Name=mad
DllName=mosp
CID_UUID=A395AF26-D4B8-4045-8C8C-40E0F0DE34A1
Flags=0
#OspServer
Name=OspServer
DllName=OspServer
CID_UUID=1ab95f8f-ccef-4d4a-8dcc-1cc5be567751
Flags=0
#FIoPi
Name=FIoPi
DllName=FIoPi
CID_UUID=b64441f0-a058-4ac6-bcf5-a8e46df3c0c2
Flags=0
#FSystemPiIpcStubReceiver
Name=FSystemPiServer
DllName=FSystemPiServer
CID_UUID=1fd7c5cf-ac9f-489b-9d00-13a816d22d8a
Flags=0
#FSystemSystemEventPortingComponen
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=fee3ccce-2aa0-46f8-90c8-021fe55df3f3
Flags=0
#FSystemAlarmPi
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=fc9f6b51-bd41-4c63-a5c0-f0dd0873d8c2
Flags=0
#FSystemAlarmPiClient
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=3952fe55-e226-4123-bc05-7cfd2fb30846
Flags=0
#FSystemAlarmPiServer
Name=FSystemPiServer
DllName=FSystemPiServer
CID_UUID=4d8663cc-97af-4873-9b0c-50fa4e89c698
Flags=0
#FSystemVibratorPi
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=ef9ef78f-D7f4-414b-9df2-1adcdcdb5ff7
Flags=0
#FSystemVibratorPiClient
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=dc621887-edde-41fb-8a7d-4ef18227f2e5
Flags=0
#FSystemVibratorPiServer
Name=FSystemPiServer
DllName=FSystemPiServer
CID_UUID=c5f8c2d1-74e7-4c13-9bb7-aba6779d1e64
Flags=0
#FSystemBatteryPortingComponent
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=51caaacf-21ff-4b3f-972f-71927be91fd1
Flags=0
#FSystemPowerManagerPortingComponent
Name=FSystemPiClient
DllName=FOspPiClient
CID_UUID=3fc83bab-b200-4d44-ab55-324ac6f8c21c0
Flags=0
#CID_TELEPHONY_CALLMANAGER_SHP
Name=FTelephonyPi
DllName=FOspPiClient
CID_UUID=6095ef26-621c-481a-b647-56765cd56c7c
Flags=0
#CID_TELEPHONY_NETWORKMANAGER_SHP
Name=FTelephonyPi
DllName=FOspPiClient
CID_UUID=af283ccb-eeff-4f7d-84c7-8a3bff8674a8
Flags=0
#CID_TELEPHONY_SIMINFO_SHP
Name=FTelephonyPi
DllName=FOspPiClient
CID_UUID=ed72fd2d-ab99-407e-b662-6779a3edd70d
Flags=0
#CID_TELEPHONY_CALLUI_SHP
Name=FTelephonyPi
DllName=FOspPiClient
CID_UUID=a34e55ec-f1d5-4fc9-a582-808a5686534a
Flags=0
#CID_MESSAGING_MESSAGE_SHP
Name=FMessagingPiClient
DllName=FOspPiClient
CID_UUID=10C5D38D-65D9-41b8-AA1F-3F4961C4ADD3
Flags=0
#CID_UIX_FACEDETECTOR_SHP
Name=FUixPiClient
DllName=FOspPiClient
CID_UUID=40414c0a-d757-4339-9d25-5be808f279cc
Flags=0
#CID_UIX_FACERECOGNIZER_SHP
Name=FUixPiClient
DllName=FOspPiClient
CID_UUID=d2822999-ede0-42d2-934b-69063bbf1392
Flags=0
#CID_UIX_MOTION_SHP
Name=FUixPiClient
DllName=FOspPiClient
CID_UUID=df436566-7646-469b-b796-8141a618065f
Flags=0
#AdHoc
Name=mcolSvcAdhoc
DllName=mcolSvcAdhoc
CID_UUID=B24989B9-2047-44e7-964E-5E88C5425A92
Flags=0
#Space
Name=mspace
DllName=mspace
CID_UUID=3C810003-F525-4bea-9D6D-F2880AB3710C
Flags=0
#Location
Name=mloc
DllName=mosp
CID_UUID=2812E7A9-7B69-4570-A65A-F763ECBFBB2E
Flags=0
#Context
Name=mcontext
DllName=mosp
CID_UUID=531B50A5-AF4A-4a74-BD0F-E49ABA19DCF1
Flags=0
#PhysicalLocator
Name=msPloc
DllName=msPloc
CID_UUID=1dda4a68-f063-4b14-abee-9c031f3eb021
Flags=0
#WeatherSensor
Name=msWeather
DllName=msWeather
CID_UUID=bf0246c0-1420-11de-8c30-0800200c9a66
Flags=0
#QueryManager
Name=mctxQpQueryManager
DllName=mctxQpQueryManager
CID_UUID=ae70cc5e-7343-45c9-9691-bfc912ec8e76
Flags=0
#Trigger
Name=mctxQpTrigger
DllName=mctxQpTrigger
CID_UUID=21c29e3d-6fe9-4b11-8e86-64a2fa2705cb		 
Flags=0
#Sync-Adaptor
Name=mctxQpSyncAdaptor
DllName=mctxQpSyncAdaptor
CID_UUID=6115f949-f7bd-457f-be6b-435a6185d4d8
Flags=0
#Aggregator
Name=mctxQpAggregator
DllName=mctxQpAggregator
CID_UUID=0b650f49-8a1d-4c5b-9a9e-177844db6d44         
Flags=0
#AdhocSpaceSpi
Name=mspaceAdhocSpi
DllName=mspaceAdhocSpi
CID_UUID=4E97E108-1E17-44a5-8DDE-899795A1AEF7
Flags=0
#IdentityManager
Name=msecIdentity
DllName=mosp
CID_UUID=E4F5BBFC-4091-4856-9921-D4F03E4D1138
Flags=0
#PrivilegeManagerServer
Name=msecPrivilegeManagerServer
DllName=msecPrivilegeManagerServer
CID_UUID=B7D17F2A-CF3D-4c6a-8A94-E0B13D26A156
Flags=0
#IdentityManagerS
Name=OspdScSecIdentityS
DllName=OspdScSecIdentityS
CID_UUID=63A83CF4-5ACE-468a-8236-C9EBA605F62D
Flags=0
#FileSys
Name=mmfs
DllName=mmfs
CID_UUID=D2CB0A9A-EC9A-4985-A5C6-A5C880116BA5
Flags=0
#FileSvr
Name=mmfs
DllName=mmfs
CID_UUID=5053AF3A-B8E5-4060-A9EF-A608DB88E0A3
Flags=0
#SpatialSearch
Name=mintUi
DllName=mintUi
CID_UUID=2c400dab-e221-45d8-b0dd-bdf2fd21bf74
Flags=0
#Persona
Name=mpcPersona
DllName=mpcPersona
CID_UUID=101B0CC7-092F-4fc7-AE77-9A1F787CBBCD
Flags=0
#Community
Name=mpcCommunity
DllName=mpcCommunity
CID_UUID=5E99BAC5-8E72-47c9-9C0C-90E5E5BF9B60
Flags=0
#Content Manager
Name=mpcContent
DllName=mpcContent
CID_UUID=86C5BCE9-ECFD-42a6-A5D2-6FE192B6D3EE
Flags=0
#slspacespi
Name=mspaceSlSpi
DllName=mspaceSlSpi
CID_UUID=9E65D317-2846-4a39-AF6E-B9C620D14B04
Flags=0
#ExportManager
Name=mctxExporter
DllName=mctxExporter
CID_UUID=7BC89411-5AE2-4344-9441-8CCF94B39820
Flags=0
#ContextImporter
Name=mctxImporter
DllName=mctxImporter
CID_UUID=25F7B253-5A36-42e6-AF51-7824905CB3B5
Flags=0
#InsertManager
Name=mctxImporter
DllName=mctxImporter
CID_UUID=1960D112-2194-4a62-8A2B-34B438A701C6
Flags=0
#ImportManager
Name=mctxImporter
DllName=mctxImporter
CID_UUID=9A8F1E55-37DE-4f85-B80F-72283835A5EE
Flags=0
#CredentialManager
Name=msecCredentialManager
DllName=mosp
CID_UUID=E62C4843-0C4B-4552-8808-B9833B163410
Flags=0
#CredentialManagerServer
Name=msecCredentialManagerServer
DllName=msecCredentialManagerServer
CID_UUID=1C3E235D-0E22-4E94-AD04-5D451475F530
Flags=0
#ServiceStub
Name=mcolSvcS
DllName=mcolSvcS
CID_UUID=8DBFE121-4402-4BDB-BAF7-1B62FAAA994B
Flags=0
#ServiceProxy
Name=mcolSvc
DllName=mcolSvc
CID_UUID=191CD464-CE0A-498A-A2F6-83EB7238B81B
Flags=0
#ContentManager
Name=mcontent
DllName=mosp
CID_UUID=4BB9C443-35A5-4cd5-92CF-B05776A14D5E
Flags=0
#RemoteContentManager
Name=mcontent
DllName=mosp
CID_UUID=E065B7FD-E345-4092-AD5F-383A8AECF14F
Flags=0
#ContentTransfer
Name=mcontent
DllName=mosp
CID_UUID=E0E2F63C-8BE5-4d79-A985-3EC1B1699EB8
Flags=0
#RssChannelInfo
Name=mcontent
DllName=mosp
CID_UUID=73F89D36-C2E8-417b-9823-8E69221A6C86
Flags=0
#FContentPi ContentUi
Name=FContentPi
DllName=FContentPi
CID_UUID=168c2a52-da0c-4706-af02-ac4123e3adbe
Flags=0
#SituationManager
Name=mctxSituationManager
DllName=mctxSituationManager
CID_UUID=70a21938-bb3e-426a-9d4e-684c106b9032
Flags=0
#Cocluster
Name=mctxsaCocluster
DllName=mctxsaCocluster
CID_UUID=42f9db23-28de-4cf6-9f28-a04869a9bed3
Flags=0
#Cocluster2
Name=mctxsaCocluster2
DllName=mctxsaCocluster2
CID_UUID=ACCA63E6-79CC-4a99-BC5A-7E3FF120FD85
Flags=0
#mctxdmAppDataImporter
Name=mctxdmAppDataImporter
DllName=mctxdmAppDataImporter
CID_UUID=15b02bb0-102e-11dd-bd0b-0800200c9a66
Flags=0
#mlocDecartaServiceProvider
Name=mlocDecartaServiceProvider
DllName=mlocDecartaServiceProvider
CID_UUID=6C1BDDAC-C24F-4782-91E6-EEA6D588CAFB
Flags=0
#mlocDecartaLandmarkStore
Name=mlocDecartaLandmarkStore
DllName=mlocDecartaLandmarkStore
CID_UUID=ca0e09a0-6dc7-11dd-ad8b-0800200c9a66
Flags=0
#mlocServiceProviderManager
Name=mlocServiceProviderManager
DllName=mlocServiceProviderManager
CID_UUID=30832712-8658-44dd-844B-5CF2784C379C
Flags=0
#PersonalContextManager
Name=mpcPersonalContextManager
DllName=mpcPersonalContextManager
CID_UUID=A50C7F2F-CB5B-4512-B13A-3AB3E984512C
Flags=0
#TemporalLoggingTask
Name=mpcTemporalLoggingTask
DllName=mpcTemporalLoggingTask
CID_UUID=E0AB4730-C4A6-4e25-B95D-453B2FB52C95
Flags=0
#Presece
Name=mpcPresence
DllName=mpcPresence
CID_UUID=9DB2C2C8-78D5-4cc4-B112-057701C7F230
Flags=0
#LifeLogger
Name=msclLifelog
DllName=mosp
CID_UUID=CE5536CB-1A9D-4e06-B3B5-4E5CC909BD9D
Flags=0
#msclLifelogPi
Name=msclLifelogPi
DllName=msclLifelogPi
CID_UUID=C69A284C-68A5-4654-B860-3CA60705B63F
Flags=0
#MessageAgent
Name=msvcMessageAgent
DllName=mosp
CID_UUID=1291e8e0-c692-11dd-ad8b-0800200c9a66
Flags=0
#PushSetting
Name=msvcMessageAgent
DllName=mosp
CID_UUID=3eef2dc3-0ec6-48be-9f8b-46a8cecda652
Flags=0
#MessageAgentServer
Name=msvcMessageAgentServer
DllName=msvcMessageAgentServer
CID_UUID=66735f02-8ec9-42c4-a29b-16381971f4e8
Flags=0
#PushSettingServer
Name=msvcMessageAgentServer
DllName=msvcMessageAgentServer
CID_UUID=4022c190-fe36-46cf-a53c-2e4211527b44
Flags=0
#ConnectionManager
Name=msvcConnectionManager
DllName=mosp
CID_UUID=4acab143-dcba-464c-8fa4-6084e8a5fb48
Flags=0
#ConnectionManagerServer
Name=msvcConnectionManagerServer
DllName=msvcConnectionManagerServer
CID_UUID=86b5ee1a-ce78-486d-a9e0-1f9e49812143
Flags=0
#Acceleration
Name=msAccel
DllName=msAccel
CID_UUID=DC3C35E0-5902-42b2-AC47-34FABF9C5A6D
Flags=0
#SocialLifelog
Name=msclLifelog
DllName=mosp
CID_UUID=E34E2B68-6238-4b7b-BE41-C4F7FE705975
Flags=0
#GlobalGroup
Name=msclGlobalGroup
DllName=msclGlobalGroup
CID_UUID=946BA4E3-6D90-4d53-AACC-5987D5AF734B
Flags=0
#FLocalesPi
Name=FLocalesPi
DllName=FOspPiClient
CID_UUID=2FFAAD8B-909D-4c92-9D6A-6A1114BFF6D1
Flags=0
#Proximity
Name=msProximity
DllName=msProximity
CID_UUID=01CCA5B4-48BA-415e-8202-EB7BA8BEBE0F
Flags=0
#Presence
Name=msclPresence
DllName=msclPresence
CID_UUID=ADB0A51C-A7EF-4095-9C48-AE8F8650241A
Flags=0
#MagneticSensor
Name=msMagnetic
DllName=msMagnetic
CID_UUID=B54ADC00-67F9-11D9-9669-0800200C9A66
Flags=0
#AmbientSensor
Name=msAmbient
DllName=msAmbient
CID_UUID=BD2D728B-8474-4a68-9D12-C74DDC840F66
Flags=0
#mdevDeviceManager
Name=mdevDeviceManager
DllName=mosp
CID_UUID=DC56508B-60C1-4940-8CC7-DC58FDA3B614
Flags=0
#FMediaPi Image
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=D32CE06F-F8B9-404a-B1EA-C277034F73D2
Flags=0
#FMediaPi Player
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=54C2F59F-A15C-4e2a-9804-767966BDE6CC
Flags=0
#FMediaPi Camera
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=B7AF8432-8B9E-4393-B82F-5EB8CCB0D475
Flags=0
#FMediaPi CameraCapability
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=84d72fcc-84c9-4b1e-a1a7-771f1fa68e06
Flags=0
#FMediaPi CameraUi
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=edb3dbd6-c04b-4e9a-bd1b-a612d0f0757e
Flags=0
#FMediaPi VideoRecorder
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=326326e2-33e2-455c-89a2-22cfd00b09fa
Flags=0
#FMediaPi AudioRecorder
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=5BADA300-CBCE-4F26-A165-C90645A43F99
Flags=0
#FMediaPi MediaUi
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=82701494-f387-4aa7-bebd-ec1aa1dcdd79
Flags=0
#FMediaPi DrmManager
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=1596D775-B35A-4a37-8101-75D1D4D9A7F1
Flags=0
#FMediaPi AudioIn
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=1696D777-B55A-4a38-9101-35D1D4D9A7F2
Flags=0
#FMediaPi AudioOut
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=1796D778-B65A-4a39-6101-15D1D4D9A7F3
Flags=0
#FMediaPi AudioPool
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=1796D779-B65A-4a39-6101-15D1D4D9A7F3
Flags=0
#FMediaPi BasicPlayerInfo
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=1796D221-B22A-4a39-6101-15D1D4D9A7F3
Flags=0
#FMediaPi AudioRouteManager
Name=FMediaPiClient
DllName=FOspPiClient
CID_UUID=1796D221-B22A-4a39-6102-15D1D4D9A7F4
Flags=0
#FGraphicsPi Bitmap
Name=FGraphicsPi
DllName=FOspPiClient
CID_UUID=DE910EB6-B2EA-4a00-A2E2-62D5524B9277
Flags=0
#FGraphicsPi Font
Name=FGraphicsPi
DllName=FOspPiClient
CID_UUID=0759F910-64C1-413d-8DE5-51ED547E7817
Flags=0
#FGraphicsPi Canvas
Name=FGraphicsPi
DllName=FOspPiClient
CID_UUID=E2550F21-7C33-40c4-8302-1C3E3883DC24
Flags=0
#FGraphicsPi EnrichedText
Name=FGraphicsPi
DllName=FOspPiClient
CID_UUID=3B0A1033-22FA-4CE9-A2B1-4A656A4EECEB
Flags=0
#FGraphicsPi TextElement
Name=FGraphicsPi
DllName=FOspPiClient
CID_UUID=399D2DB5-2383-4CB3-89AF-38C4D9399B02
Flags=0
#HMAC
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=99B79785-F47E-45D9-AA45-108B586F4B1F
Flags=0
#Symmetric
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=9971C107-2B9B-43AC-9325-D23CCD219447
Flags=0
#SecretKeyGen
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=F209DC31-2F4A-4E6A-9A7D-D8A242542E76
Flags=0
#SecureRandom
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=36AD95ED-3C93-44CE-8B12-97752AFD9290
Flags=0
#deCarta location service provider
Name=FLocationServices
DllName=FOsp
CID_UUID=b80839e1-3e66-47ef-92f5-de1bfee30295
Flags=0
#Google location service provider
Name=GoogleLBS
DllName=GoogleLBS
CID_UUID=8c9060f0-0812-11df-8a39-0800200c9a66
Flags=0
#TiltSensor
Name=msTilt
DllName=msTilt
CID_UUID=c2ff9b42-96c8-49c1-b2c3-1789147f30d5
Flags=0
#FSocialAddressbookPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=C66B7B06-6674-47b2-A134-B1BBE89BD6A6
Flags=0
#FSocialAddressbookUiPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=68916026-5887-4c02-B20D-16BB0087D8DD
Flags=0
#FSocialCalendarbookManagerPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=3EB30B11-64CA-45db-945C-E39C46F6D87E
Flags=0
#FSocialCalendarbookPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=23A53A0B-82CB-49cc-9F7D-78C31D9E7FB4
Flags=0
#FSocialCalendarbookUiPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=5B2F83C5-2AD9-48b9-B4B1-FD3DF0E37739
Flags=0
#FSocialLifelogPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=ADD46101-929E-4b5a-85ED-F7408B4BED70
Flags=0
#Board
Name=msclServices
DllName=mosp
CID_UUID=430BE9F8-4EE4-4a3e-9882-B15591688FB5
Flags=0
#Buddy
Name=msclServices
DllName=mosp
CID_UUID=F654EA2D-4908-4ef1-AAF9-FA6BBABD9D9A
Flags=0
#Privacy
Name=msclServices
DllName=mosp
CID_UUID=BC05DE71-EA03-49af-A417-7C45591034CD
Flags=0
#Profile
Name=msclServices
DllName=mosp
CID_UUID=6F15D666-986D-47f5-85F9-73D81248B8CE
Flags=0
#msclSnsGateway
Name=msclSnsGateway
DllName=msclSnsGateway
CID_UUID=B1E9CEC3-45C3-4a77-B67C-323B8A816E23
Flags=0
#GPS Sensor
Name=msGps
DllName=msGps
CID_UUID=3409CA01-D24A-4e2b-B333-82DB9041C3C3
Flags=0
#mdevDataSyncManager
Name=mdevDataSyncManager
DllName=mosp
CID_UUID=4F334FCE-76F6-490b-A6BC-A8A41ECEB62E
Flags=0
#FWebPi
Name=FWebPi
DllName=FOspPiClient
CID_UUID=ce06b40c-da00-45b6-9a0f-ebe662dafbd0
Flags=0
#FWebHistoryPi
Name=FWebPi
DllName=FOspPiClient
CID_UUID=3a8ca962-4ce4-44ac-ac08-da574a99f344
Flags=0
#FWebBrowserUiPi
Name=FWebPi
DllName=FOspPiClient
CID_UUID=99eb0f85-32d8-4714-9325-638f8dc5a915
Flags=0
#FNetPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=af5f15a1-2ed9-4bb5-aec6-3e46bd1dbaed
Flags=0
#FNetSocketsPi
Name=FNetPiSocket
DllName=FOspPiClient
CID_UUID=6bf901e1-3346-41f3-9cce-bace9942f726
Flags=0
#FNetHttpPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=6209317a-68dd-4616-8cb3-39e90b862c61
Flags=0
#FNetWifiPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=21f24ee1-2feb-4fbb-b852-c6469dd8d514
Flags=0
#FNetWifiAccountPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=857926b5-eaad-49f9-9592-b9ca73b8b93e
Flags=0
#FNetBluetoothPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=bdaa6fd1-33c3-47ff-9116-145fade3bafa
Flags=0
#FNetUiPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=30e3b514-7171-44ca-bb1b-e1f568f767d8
Flags=0
#FBluetoothUiPi
Name=FNetPiClient
DllName=FOspPiClient
CID_UUID=fd8564ac-7c67-4558-880d-d21f8591de8f
Flags=0
#FAppPi
Name=FAppPi
DllName=FOspPiClient
CID_UUID=bba64274-6621-4ed4-94e9-6f41722c9e3d
Flags=0
#SecurityProcess
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=B5230FAE-1E5A-4a21-94FD-A3A482980328
Flags=0
#hash
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=1C2810DD-C5CB-44E7-9F07-8C25942B5E3F
Flags=0
#PublicKey
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=a66ee140-ab9b-4e05-8784-f66efb5ecf64
Flags=0
#PrivateKey
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=c4511fd2-9347-4493-9862-e98e25a1388f
Flags=0
#KeyParameter
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=dfc83718-e308-4629-a059-59b981e33685
Flags=0
#KeyPairGen
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=9ed180eb-1f4e-42ac-966f-2bb8a15ff05a
Flags=0
#SecretKey
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=5355b863-2a63-4259-839c-9e87ba4501d0
Flags=0
#Asymmetric
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=b7722a4b-b9a4-482c-ad6a-18d96b371d8c
Flags=0
#Certificate
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=97144da1-cd53-46fe-96f6-5d9eada73b2d
Flags=0
#CertificateChain
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=c628c5d2-2d43-400d-a586-4a09ab5bffc4
Flags=0
#CertificateStore
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=3e01478e-5863-47c7-bf54-e39b56f95a2d
Flags=0
#CertMgrUi
Name=FSecurityPi
DllName=FOspPiClient
CID_UUID=7f5b08e0-7dfb-11df-8c4a-0800200c9a66
Flags=0
#FUixHapticPi
Name=FUixPiClient
DllName=FOspPiClient
CID_UUID=0375f72a-e363-47ef-a306-f11d4d792022
Flags=0
#FUiTouchPi 
Name=FUiPi
DllName=FUiPi
CID_UUID=583574e3-f7bc-4a7f-a70b-885dF0dda28d
Flags=0
#ClipboardPi 
Name=FUiPi
DllName=FUiPi
CID_UUID=4F439536-1AA1-481d-966D-9D19E9658053
Flags=0
#mlocLocationAgent
Name=mlocLocationAgent
DllName=mlocLocationAgent
CID_UUID=85cecb10-c430-11de-8a39-0800200c9a66
Flags=0
#CID_SEVEN_AGENT_SHP
Name=FSevenPiClient
DllName=FOspPiClient
CID_UUID=6297e969-a8af-419e-8d57-b5fe4b620fed
Flags=0
#SnsSsoManagerPi
Name=FSocialPiClient
DllName=FOspPiClient
CID_UUID=60B1C336-3DFF-4cc9-98B0-DE87359D0D34
Flags=0
#FUixTouchEffectPi
Name=FUixPiClient
DllName=FOspPiClient
CID_UUID=0E08C951-9F6E-4117-96A7-097061232DB5
Flags=0
#FLocationsPi
Name=FLocationsPi
DllName=FOspPiClient
CID_UUID=2A471660-9484-11DF-981C-0800200C9A66
Flags=0
#FAppExPi
Name=FAppExPi
DllName=FOspPiClient
CID_UUID=969cf781-c16e-41fc-938b-21d92d81d940
Flags=0
#Location
Name=mlocS
DllName=mlocS
CID_UUID=68351730-b97b-11df-851a-0800200c9a66
Flags=0