#featurelist
REMOVE_INSTALL_FAILURE_GARBAGE_FILES=1
DOWNLOAD_APPS_TO_EXTERNAL_STORAGE=1
DOWNLOAD_UI_FATAL_ERROR_DISPLAY=1
DOWNLOAD_UI_MEMORY_FULL_DISPLAY=1
NOT_CREATE_DRM_DECRYPT_FILES=1
EXCLUDE_ALREADY_INSTALLED_SIZE_FROM_REQUIRED_FREE_STORAGE=1
OPTIMIZED_SIGNIN_UI_FLOW=1
SET_INSTALL_LOCATION=1
DOWNLOAD_APPS_TO_EXTERNAL_STORAGE_WITH_INSTALLATION_PRIV=1
DELETE_ACCOUNT_SIGNIN_UI_OPERATION=1
