#Version
Version=1.0
#LIMITS
MaxPhysicalFilePathLength=256
MaxPhysicalFileNameLength=236
DefaultStoragecardRoot=/Mount/Mmc/Others/__@@bada_applications@@__
#APPLICATION
/Res=/Osp/Applications,ro
/Home/Share=/Osp/Applications,rw
/Home/Share2=/Osp/Applications,rw
/Home=/Osp/Applications,rw
/HomeExt/Share=/Mount/Mmc/Others/__@@bada_applications@@__/OspHomeExt,rw
/HomeExt/Share2=/Mount/Mmc/Others/__@@bada_applications@@__/OspHomeExt,rw
/HomeExt=/Mount/Mmc/Others/__@@bada_applications@@__/OspHomeExt,rw
/ForeignHome=/Osp/Applications/ForeignHome,rw
/EmailBox=/User/Mass/Msg,ro
/MmsBox=/User/Msg/Mms,ro
/NPKI=/Security/NPKI,rw
/Storagecard/NPKI=/Mount/Mmc/NPKI,rw
/Common=/User/Mass/Osp/Common,rw
/Share/AppControl=/Osp/Applications/AppControl,rw
/Share2Ext=/Mount/Mmc/Others/__@@bada_applications@@__/OspHomeExt,rw
/Share2=/Osp/Applications,rw
/ShareExt=/Mount/Mmc/Others/__@@bada_applications@@__/OspHomeExt,ro
/Share=/Osp/Applications,ro
#MEDIA
/Media/Images=/Media/Images,rw
/Media/Sounds=/Media/Sounds,rw
/Media/Videos=/Media/Videos,rw
/Media/Themes=/Media/Themes,rw
/Media/Others=/Media/Others,rw
/Media/Etc=/Media/Others,rw
/Media=/Media,rw
/Storagecard/DownloadedAppPackages=/Mount/Mmc/Others/DownloadedAppPackages,rw
/Storagecard/Media/Images=/Mount/Mmc/Images,rw
/Storagecard/Media/Sounds=/Mount/Mmc/Sounds,rw
/Storagecard/Media/Videos=/Mount/Mmc/Videos,rw
/Storagecard/Media/Themes=/Mount/Mmc/Themes,rw
/Storagecard/Media/Others=/Mount/Mmc/Others,rw
/Storagecard/Media=/Mount/Mmc,rw
#SYSTEM
/System=/SystemFS/User/OspSys,ro
/SystemRW=/User/OspSys,rw
/SysExt=/Osp/Applications/SysExt,rw
/Tmp=/User/Mass/Osp/Tmp,rw
/Registry=/Registry,rw
/SystemFS/Media=/SystemFS/Media,ro