#Version
Version=1

#OutputDestination
CONSOLE=YES
FILE=

#Application
INFO=YES
DEBUG=YES
EXCEPTION=YES

#Platform
INFO=
DEBUG=
EXCEPTION=YES

#PlatformModules
RUNT=
THRD=
MUTX=
EVNT=
ACTR=
TIMR=
COMP=
UTIL=
IOIO=YES
MIPC=YES
SVCF=YES
REST=YES
SECF=YES
ACCT=YES
CTXF=YES
LOCT=YES
CTXM=YES
OBJT=YES
SENS=YES
ACCS=YES
AMBS=YES
GPSS=YES
MGNS=YES
PRXS=YES
TLTS=YES
WTHS=YES
CMGR=YES
CSRC=YES
CTRS=YES
SOCL=YES
PROF=YES
LLOG=YES
PRIV=YES
SGRP=YES
SBRD=YES
BUDD=YES
SNSG=YES
DVSC=YES
DVMG=YES
DVPF=YES
DVIF=YES
ADVT=YES
TEST=YES
TETI=YES
APPS=YES
PKGS=YES
NOTI=YES
reserved=
FAd=YES
FApp=YES
FBase=YES
FBaseCol=YES
FBaseRt=YES
FBaseUtl=YES
FCom=YES
FCmrc=YES
FCmrcStr=YES
FCnt=YES
FCtx=YES
FGrp=YES
FGrpOgl=YES
FIo=YES
FLcl=YES
FLoc=YES
FLocCtrl=YES
FLocSvc=YES
FMedia=YES
FMsg=YES
FNet=YES
FNetBt=YES
FNetHttp=YES
FNetSock=YES
FNetWifi=YES
FRui=YES
FSec=YES
FSecCert=YES
FSecCrypto=YES
FScl=YES
FSclSvc=YES
FSys=YES
FTel=YES
FText=YES
FUi=YES
FUiCtrl=YES
FUix=YES
FWeb=YES
FXml=YES
FDev=YES
INFO=YES
DEBUG=YES
EXCEPTION=YES