#mappserver
Name=mappserver
CID_UUID=33c84e7e-6843-4174-a362-d74f72f4a2fe
LAUNCH=1
#mappscchromeipcservermanager
Name=scchromeipcservermanager
CID_UUID=236f1c9c-f552-4adf-bc72-c8c45ce4a49d
LAUNCH=1
#mappserverchromeipcstub
Name=mappserverchromeipcstub
CID_UUID=ec62f26f-a949-4327-baf9-236c3deb2972
LAUNCH=1
#msysserverstub
Name=msysserverstub
CID_UUID=dce74bcd-6096-4617-a8a1-7f23f3da9e34
LAUNCH=1
#OafServerManger
Name=OafServerManager
CID_UUID=1ab95f8f-ccef-4d4a-8dcc-1cc5be567751
LAUNCH=1
