#systeminfo
ScreenHeight=800
ScreenWidth=480
ScreenDPI=282
ScreenBitsPerPixel=32
PlatformVersion=1.2
PlatformVersionMajor=1
PlatformVersionMinor=2
PlatformVersionIdentifier=0
PlatformVersionInternal=0
OpenGLESVersion=1.1/2.0
KeyboardType=None
NetworkType=GPRS
BluetoothSupported=Supported
WiFiSupported=Supported
GPSSupported=Supported
WPSSupported=Supported
HapticSupported=Supported
FmRadioSupported=TRUE
TvOutSupported=TRUE
CameraCount=2
VideoRecordingDefaultCodec=VIDEO_CODEC_MPEG4SP
VideoRecordingCodecs_Count=2
VideoRecordingCodecs0=VIDEO_CODEC_MPEG4SP
VideoRecordingCodecs1=VIDEO_CODEC_H263
VideoRecordingDefaultFormat=MP4
AudioRecordingDefaultFormat=AMR
SamsungAppsAppId=1rfjf7285p
