#KonaConfigSection
KonaC0=http://hub-odc.samsungapps.com/ods.as
KonaC1=0
KonaC2=210.118.57.11
KonaC3=http://apps-dn.stg.ospserver.net
KonaC4=http://210.118.57.13/ods.as
KonaC5=/Home/Img/
KonaC6=/Home/App/
KonaC7=/Home/Doc/
KonaC8=/Home/Temp/
KonaC9= 
KonaC10= 
KonaC11= 
KonaC12= 
KonaC13= 
KonaC14= 
KonaC15= 
KonaC16= 
KonaC17=0
KonaC18=20
KonaC19= 
KonaC20= 
KonaC21= 
KonaC22= 
KonaC23= 
KonaC24= 
KonaC25=0
KonaC26=0
KonaC27=0
KonaC28=168.219.61.250:8080
KonaC29=5120
KonaC30=http://210.118.57.15/ods.as
KonaC31=http://210.118.57.9/ods.as
KonaC32=0
KonaC33=1
KonaC34= 
KonaC35=1
KonaC36= 
KonaC37= 
